- id: check-commit-message
  name: check-commit-message
  description: Commit message should be in the format "[Add|Merge|Fix|Remove|Refactor|Change|Update] <text length between 10 and 80>"
  entry: \A(?!(Add|Merge|Fix|Remove|Refactor|Change|Update)\s.{8,80}[\w'"!?]$)
  args: [--multiline]
  language: pygrep